version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "automated"