/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Message: typeof import('./src/components/service/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VMain: typeof import('vuetify/lib')['VMain']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
  }
}
